### ISSUE TITLE
Add repository description?

### ISSUE THREAD

**Issue by joshuacc** [Chunjee/stringc.ahk#1]
When looking over the [ahkpm Packages page](https://ahkpm.dev/packages), I noticed that stringc.ahk doesn't have a description listed, because that is currently pulled from the GitHub API.

Adding an issue on ahkpm to mention that in the publishing guide, but if you add a description to this repository, it should show up on ahkpm.dev in the next 24 hours. :)

**Comment by Chunjee** [comment]
Thanks I will look at that option

However, it is too bad it can't use what's in the ahkpm.json as a fallback

**Comment by joshuacc** [comment]
Good idea. I've created another issue to track that.

**Comment by Chunjee** [comment]
done

> A v1 AutoHotkey package that finds degree of similarity between strings, based on Sørensen–Dice coefficient, which is mostly better than Levenshtein distance.
